using Anaconda as the env to run the OpenStack components

diff --git a/stackrc b/stackrc
--- a/stackrc
+++ b/stackrc
@@ -39,9 +39,9 @@ SUBUNIT_OUTPUT=${DEST}/devstack.subunit
 
 # Determine stack user
 if [[ $EUID -eq 0 ]]; then
-    STACK_USER=stack
+  STACK_USER=stack
 else
-    STACK_USER=$(whoami)
+  STACK_USER=$(whoami)
 fi
 
 # Specify region name Region
@@ -61,25 +61,25 @@ KEYSTONE_REGION_NAME=${KEYSTONE_REGION_NAME:-$REGION_NAME}
 #  [[local|localrc]]
 #  enable_service s-proxy s-object s-container s-account
 # This allows us to pass ``ENABLED_SERVICES``
-if ! isset ENABLED_SERVICES ; then
-    # Keystone - nothing works without keystone
-    ENABLED_SERVICES=key
-    # Nova - services to support libvirt based openstack clouds
-    ENABLED_SERVICES+=,n-api,n-cpu,n-cond,n-sch,n-novnc,n-api-meta
-    # Placement service needed for Nova
-    ENABLED_SERVICES+=,placement-api,placement-client
-    # Glance services needed for Nova
-    ENABLED_SERVICES+=,g-api
-    # Cinder
-    ENABLED_SERVICES+=,c-sch,c-api,c-vol
-    # OVN
-    ENABLED_SERVICES+=,ovn-controller,ovn-northd,ovs-vswitchd,ovsdb-server
-    # Neutron
-    ENABLED_SERVICES+=,q-svc,q-ovn-metadata-agent
-    # Dashboard
-    ENABLED_SERVICES+=,horizon
-    # Additional services
-    ENABLED_SERVICES+=,rabbit,tempest,mysql,etcd3,dstat
+if ! isset ENABLED_SERVICES; then
+  # Keystone - nothing works without keystone
+  ENABLED_SERVICES=key
+  # Nova - services to support libvirt based openstack clouds
+  ENABLED_SERVICES+=,n-api,n-cpu,n-cond,n-sch,n-novnc,n-api-meta
+  # Placement service needed for Nova
+  ENABLED_SERVICES+=,placement-api,placement-client
+  # Glance services needed for Nova
+  ENABLED_SERVICES+=,g-api
+  # Cinder
+  ENABLED_SERVICES+=,c-sch,c-api,c-vol
+  # OVN
+  ENABLED_SERVICES+=,ovn-controller,ovn-northd,ovs-vswitchd,ovsdb-server
+  # Neutron
+  ENABLED_SERVICES+=,q-svc,q-ovn-metadata-agent
+  # Dashboard
+  ENABLED_SERVICES+=,horizon
+  # Additional services
+  ENABLED_SERVICES+=,rabbit,tempest,mysql,etcd3,dstat
 fi
 
 # Global toggle for enabling services under mod_wsgi. If this is set to
@@ -93,11 +93,11 @@ NOVA_ENABLED_APIS=osapi_compute,metadata
 
 # allow local overrides of env variables, including repo config
 if [[ -f $RC_DIR/localrc ]]; then
-    # Old-style user-supplied config
-    source $RC_DIR/localrc
+  # Old-style user-supplied config
+  source $RC_DIR/localrc
 elif [[ -f $RC_DIR/.localrc.auto ]]; then
-    # New-style user-supplied config extracted from local.conf
-    source $RC_DIR/.localrc.auto
+  # New-style user-supplied config extracted from local.conf
+  source $RC_DIR/.localrc.auto
 fi
 
 # CELLSV2_SETUP - how we should configure services with cells v2
@@ -114,13 +114,12 @@ HORIZON_APACHE_ROOT="/dashboard"
 # Whether to use user specific units for running services or global ones.
 USER_UNITS=$(trueorfalse False USER_UNITS)
 if [[ "$USER_UNITS" == "True" ]]; then
-    SYSTEMD_DIR="$HOME/.local/share/systemd/user"
-    SYSTEMCTL="systemctl --user"
+  SYSTEMD_DIR="$HOME/.local/share/systemd/user"
+  SYSTEMCTL="systemctl --user"
 else
-    SYSTEMD_DIR="/etc/systemd/system"
-    SYSTEMCTL="sudo systemctl"
+  SYSTEMD_DIR="/etc/systemd/system"
+  SYSTEMCTL="sudo systemctl"
 fi
-
 
 # Whether or not to enable Kernel Samepage Merging (KSM) if available.
 # This allows programs that mark their memory as mergeable to share
@@ -132,7 +131,7 @@ ENABLE_KSM=$(trueorfalse True ENABLE_KSM)
 
 # Passwords generated by interactive devstack runs
 if [[ -r $RC_DIR/.localrc.password ]]; then
-    source $RC_DIR/.localrc.password
+  source $RC_DIR/.localrc.password
 fi
 
 # Control whether Python 3 should be used at all.
@@ -154,9 +153,9 @@ export VIRTUALENV_CMD="python3 -m venv"
 # codes should be omitted.
 # Simply override LOG_COLOR if your environment is different.
 if [ -t 1 ]; then
-    _LOG_COLOR_DEFAULT=True
+  _LOG_COLOR_DEFAULT=True
 else
-    _LOG_COLOR_DEFAULT=False
+  _LOG_COLOR_DEFAULT=False
 fi
 
 # Use color for logging output (only available if syslog is not used)
@@ -164,15 +163,15 @@ LOG_COLOR=$(trueorfalse $_LOG_COLOR_DEFAULT LOG_COLOR)
 
 # Make tracing more educational
 if [[ "$LOG_COLOR" == "True" ]]; then
-    # tput requires TERM or -T.  If neither is present, use vt100, a
-    # no-frills least common denominator supported everywhere.
-    TPUT_T=
-    if ! [ $TERM ]; then
-        TPUT_T='-T vt100'
-    fi
-    export PS4='+\[$(tput '$TPUT_T' setaf 242)\]$(short_source)\[$(tput '$TPUT_T' sgr0)\] '
+  # tput requires TERM or -T.  If neither is present, use vt100, a
+  # no-frills least common denominator supported everywhere.
+  TPUT_T=
+  if ! [ $TERM ]; then
+    TPUT_T='-T vt100'
+  fi
+  export PS4='+\[$(tput '$TPUT_T' setaf 242)\]$(short_source)\[$(tput '$TPUT_T' sgr0)\] '
 else
-    export PS4='+ $(short_source):   '
+  export PS4='+ $(short_source):   '
 fi
 
 # Configure Identity API version
@@ -303,7 +302,6 @@ TEMPEST_REPO=${TEMPEST_REPO:-${GIT_BASE}/openstack/tempest.git}
 TEMPEST_BRANCH=${TEMPEST_BRANCH:-$BRANCHLESS_TARGET_BRANCH}
 TEMPEST_VENV_UPPER_CONSTRAINTS=${TEMPEST_VENV_UPPER_CONSTRAINTS:-master}
 
-
 ##############
 #
 #  OpenStack Client Library Components
@@ -363,7 +361,6 @@ GITDIR["python-openstackclient"]=$DEST/python-openstackclient
 # placement-api CLI
 GITREPO["osc-placement"]=${OSC_PLACEMENT_REPO:-${GIT_BASE}/openstack/osc-placement.git}
 GITBRANCH["osc-placement"]=${OSC_PLACEMENT_BRANCH:-$TARGET_BRANCH}
-
 
 ###################
 #
@@ -492,7 +489,6 @@ GITBRANCH["tooz"]=${TOOZ_BRANCH:-$TARGET_BRANCH}
 GITREPO["pbr"]=${PBR_REPO:-${GIT_BASE}/openstack/pbr.git}
 GITBRANCH["pbr"]=${PBR_BRANCH:-$BRANCHLESS_TARGET_BRANCH}
 
-
 ##################
 #
 #  Libraries managed by OpenStack programs (non oslo)
@@ -593,7 +589,6 @@ OCC_BRANCH=${OCC_BRANCH:-$TRAILING_TARGET_BRANCH}
 ORC_REPO=${ORC_REPO:-${GIT_BASE}/openstack/os-refresh-config.git}
 ORC_BRANCH=${ORC_BRANCH:-$TRAILING_TARGET_BRANCH}
 
-
 #################
 #
 #  3rd Party Components (non pip installable)
@@ -626,31 +621,31 @@ ENABLE_VOLUME_MULTIATTACH=$(trueorfalse False ENABLE_VOLUME_MULTIATTACH)
 DEFAULT_VIRT_DRIVER=libvirt
 VIRT_DRIVER=${VIRT_DRIVER:-$DEFAULT_VIRT_DRIVER}
 case "$VIRT_DRIVER" in
-    ironic|libvirt)
-        LIBVIRT_TYPE=${LIBVIRT_TYPE:-kvm}
-        LIBVIRT_CPU_MODE=${LIBVIRT_CPU_MODE:-custom}
-        LIBVIRT_CPU_MODEL=${LIBVIRT_CPU_MODEL:-Nehalem}
-        if [[ "$os_VENDOR" =~ (Debian|Ubuntu) ]]; then
-            # The groups change with newer libvirt. Older Ubuntu used
-            # 'libvirtd', but now uses libvirt like Debian. Do a quick check
-            # to see if libvirtd group already exists to handle grenade's case.
-            LIBVIRT_GROUP=$(cut -d ':' -f 1 /etc/group | grep 'libvirtd$' || true)
-            LIBVIRT_GROUP=${LIBVIRT_GROUP:-libvirt}
-        else
-            LIBVIRT_GROUP=libvirtd
-        fi
-        ;;
-    lxd)
-        LXD_GROUP=${LXD_GROUP:-"lxd"}
-        ;;
-    docker|zun)
-        DOCKER_GROUP=${DOCKER_GROUP:-"docker"}
-        ;;
-    fake)
-        NUMBER_FAKE_NOVA_COMPUTE=${NUMBER_FAKE_NOVA_COMPUTE:-1}
-        ;;
-    *)
-        ;;
+ironic | libvirt)
+  LIBVIRT_TYPE=${LIBVIRT_TYPE:-kvm}
+  LIBVIRT_CPU_MODE=${LIBVIRT_CPU_MODE:-custom}
+  LIBVIRT_CPU_MODEL=${LIBVIRT_CPU_MODEL:-Nehalem}
+  if [[ "$os_VENDOR" =~ (Debian|Ubuntu) ]]; then
+    # The groups change with newer libvirt. Older Ubuntu used
+    # 'libvirtd', but now uses libvirt like Debian. Do a quick check
+    # to see if libvirtd group already exists to handle grenade's case.
+    LIBVIRT_GROUP=$(cut -d ':' -f 1 /etc/group | grep 'libvirtd$' || true)
+    LIBVIRT_GROUP=${LIBVIRT_GROUP:-libvirt}
+  else
+    LIBVIRT_GROUP=libvirtd
+  fi
+  ;;
+lxd)
+  LXD_GROUP=${LXD_GROUP:-"lxd"}
+  ;;
+docker | zun)
+  DOCKER_GROUP=${DOCKER_GROUP:-"docker"}
+  ;;
+fake)
+  NUMBER_FAKE_NOVA_COMPUTE=${NUMBER_FAKE_NOVA_COMPUTE:-1}
+  ;;
+*) ;;
+
 esac
 
 # Images
@@ -683,33 +678,37 @@ CIRROS_ARCH=${CIRROS_ARCH:-$(uname -m)}
 # ``IMAGE_URLS`` to be set in the `localrc` section of ``local.conf``.
 DOWNLOAD_DEFAULT_IMAGES=$(trueorfalse True DOWNLOAD_DEFAULT_IMAGES)
 if [[ "$DOWNLOAD_DEFAULT_IMAGES" == "True" ]]; then
-    if [[ -n "$IMAGE_URLS" ]]; then
-        IMAGE_URLS+=","
-    fi
-    case "$VIRT_DRIVER" in
-        libvirt)
-            case "$LIBVIRT_TYPE" in
-                lxc) # the cirros root disk in the uec tarball is empty, so it will not work for lxc
-                    DEFAULT_IMAGE_NAME=${DEFAULT_IMAGE_NAME:-cirros-${CIRROS_VERSION}-${CIRROS_ARCH}-rootfs}
-                    DEFAULT_IMAGE_FILE_NAME=${DEFAULT_IMAGE_FILE_NAME:-cirros-${CIRROS_VERSION}-${CIRROS_ARCH}-rootfs.img.gz}
-                    IMAGE_URLS+="http://download.cirros-cloud.net/${CIRROS_VERSION}/${DEFAULT_IMAGE_FILE_NAME}";;
-                *) # otherwise, use the qcow image
-                    DEFAULT_IMAGE_NAME=${DEFAULT_IMAGE_NAME:-cirros-${CIRROS_VERSION}-${CIRROS_ARCH}-disk}
-                    DEFAULT_IMAGE_FILE_NAME=${DEFAULT_IMAGE_FILE_NAME:-cirros-${CIRROS_VERSION}-${CIRROS_ARCH}-disk.img}
-                    IMAGE_URLS+="http://download.cirros-cloud.net/${CIRROS_VERSION}/${DEFAULT_IMAGE_FILE_NAME}";;
-                esac
-            ;;
-        vsphere)
-            DEFAULT_IMAGE_NAME=${DEFAULT_IMAGE_NAME:-cirros-0.3.2-i386-disk.vmdk}
-            DEFAULT_IMAGE_FILE_NAME=${DEFAULT_IMAGE_FILE_NAME:-$DEFAULT_IMAGE_NAME}
-            IMAGE_URLS+="http://partnerweb.vmware.com/programs/vmdkimage/${DEFAULT_IMAGE_FILE_NAME}";;
-        fake)
-            # Use the same as the default for libvirt
-            DEFAULT_IMAGE_NAME=${DEFAULT_IMAGE_NAME:-cirros-${CIRROS_VERSION}-${CIRROS_ARCH}-disk}
-            DEFAULT_IMAGE_FILE_NAME=${DEFAULT_IMAGE_FILE_NAME:-cirros-${CIRROS_VERSION}-${CIRROS_ARCH}-disk.img}
-            IMAGE_URLS+="http://download.cirros-cloud.net/${CIRROS_VERSION}/${DEFAULT_IMAGE_FILE_NAME}";;
+  if [[ -n "$IMAGE_URLS" ]]; then
+    IMAGE_URLS+=","
+  fi
+  case "$VIRT_DRIVER" in
+  libvirt)
+    case "$LIBVIRT_TYPE" in
+    lxc) # the cirros root disk in the uec tarball is empty, so it will not work for lxc
+      DEFAULT_IMAGE_NAME=${DEFAULT_IMAGE_NAME:-cirros-${CIRROS_VERSION}-${CIRROS_ARCH}-rootfs}
+      DEFAULT_IMAGE_FILE_NAME=${DEFAULT_IMAGE_FILE_NAME:-cirros-${CIRROS_VERSION}-${CIRROS_ARCH}-rootfs.img.gz}
+      IMAGE_URLS+="http://download.cirros-cloud.net/${CIRROS_VERSION}/${DEFAULT_IMAGE_FILE_NAME}"
+      ;;
+    *) # otherwise, use the qcow image
+      DEFAULT_IMAGE_NAME=${DEFAULT_IMAGE_NAME:-cirros-${CIRROS_VERSION}-${CIRROS_ARCH}-disk}
+      DEFAULT_IMAGE_FILE_NAME=${DEFAULT_IMAGE_FILE_NAME:-cirros-${CIRROS_VERSION}-${CIRROS_ARCH}-disk.img}
+      IMAGE_URLS+="http://download.cirros-cloud.net/${CIRROS_VERSION}/${DEFAULT_IMAGE_FILE_NAME}"
+      ;;
     esac
-    DOWNLOAD_DEFAULT_IMAGES=False
+    ;;
+  vsphere)
+    DEFAULT_IMAGE_NAME=${DEFAULT_IMAGE_NAME:-cirros-0.3.2-i386-disk.vmdk}
+    DEFAULT_IMAGE_FILE_NAME=${DEFAULT_IMAGE_FILE_NAME:-$DEFAULT_IMAGE_NAME}
+    IMAGE_URLS+="http://partnerweb.vmware.com/programs/vmdkimage/${DEFAULT_IMAGE_FILE_NAME}"
+    ;;
+  fake)
+    # Use the same as the default for libvirt
+    DEFAULT_IMAGE_NAME=${DEFAULT_IMAGE_NAME:-cirros-${CIRROS_VERSION}-${CIRROS_ARCH}-disk}
+    DEFAULT_IMAGE_FILE_NAME=${DEFAULT_IMAGE_FILE_NAME:-cirros-${CIRROS_VERSION}-${CIRROS_ARCH}-disk.img}
+    IMAGE_URLS+="http://download.cirros-cloud.net/${CIRROS_VERSION}/${DEFAULT_IMAGE_FILE_NAME}"
+    ;;
+  esac
+  DOWNLOAD_DEFAULT_IMAGES=False
 fi
 
 # This is a comma separated list of extra URLS to be listed for
@@ -729,26 +728,26 @@ ETCD_SHA256_PPC64=${ETCD_SHA256_PPC64:-"77f807b1b51abbf51e020bb05bdb8ce088cb5826
 ETCD_SHA256_S390X=${ETCD_SHA256_S390X:-""}
 # Make sure etcd3 downloads the correct architecture
 if is_arch "x86_64"; then
-    ETCD_ARCH="amd64"
-    ETCD_SHA256=${ETCD_SHA256:-$ETCD_SHA256_AMD64}
+  ETCD_ARCH="amd64"
+  ETCD_SHA256=${ETCD_SHA256:-$ETCD_SHA256_AMD64}
 elif is_arch "aarch64"; then
-    ETCD_ARCH="arm64"
-    ETCD_SHA256=${ETCD_SHA256:-$ETCD_SHA256_ARM64}
+  ETCD_ARCH="arm64"
+  ETCD_SHA256=${ETCD_SHA256:-$ETCD_SHA256_ARM64}
 elif is_arch "ppc64le"; then
-    ETCD_ARCH="ppc64le"
-    ETCD_SHA256=${ETCD_SHA256:-$ETCD_SHA256_PPC64}
+  ETCD_ARCH="ppc64le"
+  ETCD_SHA256=${ETCD_SHA256:-$ETCD_SHA256_PPC64}
 elif is_arch "s390x"; then
-    # An etcd3 binary for s390x is not available on github like it is
-    # for other arches. Only continue if a custom download URL was
-    # provided.
-    if [[ -n "${ETCD_DOWNLOAD_URL}" ]]; then
-        ETCD_ARCH="s390x"
-        ETCD_SHA256=${ETCD_SHA256:-$ETCD_SHA256_S390X}
-    else
-        exit_distro_not_supported "etcd3. No custom ETCD_DOWNLOAD_URL provided."
-    fi
+  # An etcd3 binary for s390x is not available on github like it is
+  # for other arches. Only continue if a custom download URL was
+  # provided.
+  if [[ -n "${ETCD_DOWNLOAD_URL}" ]]; then
+    ETCD_ARCH="s390x"
+    ETCD_SHA256=${ETCD_SHA256:-$ETCD_SHA256_S390X}
+  else
+    exit_distro_not_supported "etcd3. No custom ETCD_DOWNLOAD_URL provided."
+  fi
 else
-    exit_distro_not_supported "invalid hardware type - $ETCD_ARCH"
+  exit_distro_not_supported "invalid hardware type - $ETCD_ARCH"
 fi
 ETCD_PORT=${ETCD_PORT:-2379}
 ETCD_PEER_PORT=${ETCD_PEER_PORT:-2380}
@@ -765,9 +764,9 @@ MEMCACHE_SERVERS=${MEMCACHE_SERVERS:-"localhost:11211"}
 
 # Detect duplicate values in IMAGE_URLS
 for image_url in ${IMAGE_URLS//,/ }; do
-    if [ $(echo "$IMAGE_URLS" | grep -o -F "$image_url" | wc -l) -gt 1 ]; then
-        die $LINENO "$image_url is duplicate, please remove it from IMAGE_URLS."
-    fi
+  if [ $(echo "$IMAGE_URLS" | grep -o -F "$image_url" | wc -l) -gt 1 ]; then
+    die $LINENO "$image_url is duplicate, please remove it from IMAGE_URLS."
+  fi
 done
 
 # 30Gb default volume backing file size
@@ -793,7 +792,7 @@ SERVICE_PROTOCOL=${SERVICE_PROTOCOL:-http}
 # the memory used where there are a large number of CPUs present
 # (the default number of workers for many services is the number of CPUs)
 # Also sets the minimum number of workers to 2.
-API_WORKERS=${API_WORKERS:=$(( ($(nproc)/4)<2 ? 2 : ($(nproc)/4) ))}
+API_WORKERS=${API_WORKERS:=$((($(nproc) / 4) < 2 ? 2 : ($(nproc) / 4)))}
 
 # Service startup timeout
 SERVICE_TIMEOUT=${SERVICE_TIMEOUT:-60}
@@ -836,7 +835,7 @@ HOST_IPV6=${HOST_IPV6:-}
 
 HOST_IP=$(get_default_host_ip "$FIXED_RANGE" "$FLOATING_RANGE" "$HOST_IP_IFACE" "$HOST_IP" "inet")
 if [ "$HOST_IP" == "" ]; then
-    die $LINENO "Could not determine host ip address.  See local.conf for suggestions on setting HOST_IP."
+  die $LINENO "Could not determine host ip address.  See local.conf for suggestions on setting HOST_IP."
 fi
 
 HOST_IPV6=$(get_default_host_ip "" "" "$HOST_IP_IFACE" "$HOST_IPV6" "inet6")
@@ -854,23 +853,23 @@ SERVICE_IP_VERSION=${SERVICE_IP_VERSION:-4}
 # multiple calls into keystone to register endpoints, so for now let's
 # just support one or the other.
 if [[ $SERVICE_IP_VERSION != "4" ]] && [[ $SERVICE_IP_VERSION != "6" ]]; then
-    die $LINENO "SERVICE_IP_VERSION must be either 4 or 6"
+  die $LINENO "SERVICE_IP_VERSION must be either 4 or 6"
 fi
 
 if [[ "$SERVICE_IP_VERSION" == 4 ]]; then
-    DEF_SERVICE_HOST=$HOST_IP
-    DEF_SERVICE_LOCAL_HOST=127.0.0.1
-    DEF_SERVICE_LISTEN_ADDRESS=0.0.0.0
+  DEF_SERVICE_HOST=$HOST_IP
+  DEF_SERVICE_LOCAL_HOST=127.0.0.1
+  DEF_SERVICE_LISTEN_ADDRESS=0.0.0.0
 fi
 
 if [[ "$SERVICE_IP_VERSION" == 6 ]]; then
-    if [ "$HOST_IPV6" == "" ]; then
-        die $LINENO "Could not determine host IPv6 address.  See local.conf for suggestions on setting HOST_IPV6."
-    fi
+  if [ "$HOST_IPV6" == "" ]; then
+    die $LINENO "Could not determine host IPv6 address.  See local.conf for suggestions on setting HOST_IPV6."
+  fi
 
-    DEF_SERVICE_HOST=[$HOST_IPV6]
-    DEF_SERVICE_LOCAL_HOST=::1
-    DEF_SERVICE_LISTEN_ADDRESS="[::]"
+  DEF_SERVICE_HOST=[$HOST_IPV6]
+  DEF_SERVICE_LOCAL_HOST=::1
+  DEF_SERVICE_LISTEN_ADDRESS="[::]"
 fi
 
 # This is either 0.0.0.0 for IPv4 or [::] for IPv6
@@ -888,20 +887,20 @@ TUNNEL_IP_VERSION=${TUNNEL_IP_VERSION:-4}
 
 # Validate TUNNEL_IP_VERSION
 if [[ $TUNNEL_IP_VERSION != "4" ]] && [[ $TUNNEL_IP_VERSION != "6" ]]; then
-    die $LINENO "TUNNEL_IP_VERSION must be either 4 or 6"
+  die $LINENO "TUNNEL_IP_VERSION must be either 4 or 6"
 fi
 
 if [[ "$TUNNEL_IP_VERSION" == 4 ]]; then
-    DEF_TUNNEL_ENDPOINT_IP=$HOST_IP
+  DEF_TUNNEL_ENDPOINT_IP=$HOST_IP
 fi
 
 if [[ "$TUNNEL_IP_VERSION" == 6 ]]; then
-    # Only die if the user has not over-ridden the endpoint IP
-    if [[ "$HOST_IPV6" == "" ]] && [[ "$TUNNEL_ENDPOINT_IP" == "" ]]; then
-        die $LINENO "Could not determine host IPv6 address.  See local.conf for suggestions on setting HOST_IPV6."
-    fi
+  # Only die if the user has not over-ridden the endpoint IP
+  if [[ "$HOST_IPV6" == "" ]] && [[ "$TUNNEL_ENDPOINT_IP" == "" ]]; then
+    die $LINENO "Could not determine host IPv6 address.  See local.conf for suggestions on setting HOST_IPV6."
+  fi
 
-    DEF_TUNNEL_ENDPOINT_IP=$HOST_IPV6
+  DEF_TUNNEL_ENDPOINT_IP=$HOST_IPV6
 fi
 
 # Allow the use of an alternate address for tunnel endpoints.
@@ -932,20 +931,20 @@ RECREATE_KEYSTONE_DB=$(trueorfalse True RECREATE_KEYSTONE_DB)
 
 # Set up new logging defaults
 if [[ -z "${LOGDIR:-}" ]]; then
-    default_logdir=$DEST/logs
-    if [[ -z "${LOGFILE:-}" ]]; then
-        # Nothing is set, we need a default
-        LOGDIR="$default_logdir"
-    else
-        # Set default LOGDIR
-        LOGDIR="${LOGFILE%/*}"
-        logfile="${LOGFILE##*/}"
-        if [[ -z "$LOGDIR" || "$LOGDIR" == "$logfile" ]]; then
-            # LOGFILE had no path, set a default
-            LOGDIR="$default_logdir"
-        fi
+  default_logdir=$DEST/logs
+  if [[ -z "${LOGFILE:-}" ]]; then
+    # Nothing is set, we need a default
+    LOGDIR="$default_logdir"
+  else
+    # Set default LOGDIR
+    LOGDIR="${LOGFILE%/*}"
+    logfile="${LOGFILE##*/}"
+    if [[ -z "$LOGDIR" || "$LOGDIR" == "$logfile" ]]; then
+      # LOGFILE had no path, set a default
+      LOGDIR="$default_logdir"
     fi
-    unset default_logdir logfile
+  fi
+  unset default_logdir logfile
 fi
 
 # ``LOGDIR`` is always set at this point so it is not useful as a 'enable' for service logs
@@ -957,7 +956,8 @@ ULIMIT_NOFILE=${ULIMIT_NOFILE:-2048}
 # mode: shell-script
 # End:
 
-
-
 ############################################ CUSTOMIZING ############################################
 DOCKERIZED_DATABASE=${DOCKERIZED_DATABASE:-False}
+CONDA_ENABLED=${CONDA_ENABLED:-False}
+CONDA_ENV_NAME=${CONDA_ENV_NAME:-}
+CONDA_PYTHON_VERSION=${CONDA_PYTHON_VERSION:-3.8}
